Vagrant.configure('2') do |config|

    config.env.enable
    config.vm.boot_timeout = 1200

    config.vm.define 'gitlab_srv' do |gitlab_srv|

        gitlab_srv.vm.box = 'ubuntu/focal64'
        gitlab_srv.vm.hostname = 'gitlab-srv'
        gitlab_srv.vm.network 'public_network', ip: ENV['GITLAB_IP'], bridge: ENV['INTERFACE_LAN']
        gitlab_srv.vm.network 'forwarded_port', guest: 80, host: 8080

        gitlab_srv.vm.provision 'shell', inline: 'sudo timedatectl set-timezone America/Sao_Paulo'
        gitlab_srv.vm.provision 'shell', inline: 'sudo cp /vagrant/files/crontab.sh /etc/cron.hourly/'
        gitlab_srv.vm.provision 'shell', inline: 'sudo apt-get install -y ca-certificates curl openssh-server'
        gitlab_srv.vm.provision 'shell', inline: 'sudo curl -sS https://packages.gitlab.com/install/repositories/gitlab/gitlab-ce/script.deb.sh | sudo bash'
        gitlab_srv.vm.provision 'shell', inline: 'sudo apt-get update'
        gitlab_srv.vm.provision 'shell', inline: 'sudo apt-get install -y gitlab-ce'
        gitlab_srv.vm.provision 'shell', inline: 'sudo mv /etc/gitlab/gitlab.rb /etc/gitlab/gitlab.rb.old'
        gitlab_srv.vm.provision 'shell', inline: 'sudo cp /vagrant/files/gitlab.rb /etc/gitlab/'
        gitlab_srv.vm.provision 'shell', inline: 'sudo gitlab-ctl reconfigure'

        gitlab_srv.vm.provider 'virtualbox' do |vb|
            vb.memory = 4096
            vb.cpus = 4
            vb.name = 'gitlab-srv'
            vb.customize ['modifyvm', :id, '--nicpromisc2', 'allow-all']

        end

    end

end